AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: The Game Checker V1 api gateway code

Parameters:
  HttpApi:
    Type: String
    Description: The ID of the API Gateway this method should be attached to.
  RootResourceId:
    Type: String
    Description: The ID of the root resource of the api gateway
  AuthorizerId:
    Type: String
    Description: The ID of the authorizer
  TableName:
    Type: String
    Description: The name of the database table
  Prefix:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]*"

Resources:
  # Route for /v1
  V1Route:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'ANY /v1'

  # Steam:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: ./steam/template.yaml
  #     Parameters:
  #       HttpApi: !Ref HttpApiId
  #       RootResourceId: !GetAtt V1Path.ResourceId
  #       AuthorizerId: !Ref AuthorizerId
  #       TableName: !Ref TableName
  #       Prefix: !Ref Prefix