AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: The Game Checker HTTP API with Google JWT Auth

Parameters:
  TableName:
    Type: String
    Description: The name of the table to load data into
  Prefix:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]*"
  GoogleClientId:
    Type: String
    Description: Your Google OAuth Client ID
    Default: 526294520699-n3mfhhfmf1ucqhmbgj1kqir4i5f9fb2j.apps.googleusercontent.com

Resources:
  # Create the HTTP API
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "${Prefix}HttpApi"
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - OPTIONS
        AllowHeaders:
          - '*'

  # Google JWT Authorizer
  GoogleJWTAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      ApiId: !Ref HttpApi
      AuthorizerType: JWT
      IdentitySource:
        - "$request.header.Authorization"
      JwtConfiguration:
        Issuer: "https://accounts.google.com"
        Audience:
          - !Ref GoogleClientId
      Name: GoogleJWTAuthorizer

  Health:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../api/health/template.yaml
      Parameters:
        HttpApi: !Ref HttpApi
        Prefix: !Ref Prefix

  V1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../api/v1/template.yaml
      Parameters:
        HttpApi: !Ref HttpApi
        Prefix: !Ref Prefix
        AuthorizerId: !Ref GoogleJWTAuthorizer

Outputs:
  HttpApiId:
    Description: ID of the HTTP API
    Value: !Ref HttpApi
  HttpApiInvokeUrl:
    Description: Invoke URL of the HTTP API
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"