AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: The Game Checker api method

Parameters:
  ApiGatewayId:
    Type: String
    Description: The ID of the API Gateway this method should be attached to.
  Prefix:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]*"
  ApiGatewayResource:
    Type: String
    Description: The api gateway resource to attach the endpoint to

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ["${Prefix}GetHealth_V1", { Prefix: !Ref Prefix }]
      CodeUri: ./dist
      Handler: index.handler
      Runtime: nodejs22.x
      Architectures:
        - arm64
      Role: !GetAtt LambdaRole.Arn

  GetEndpoint:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayId
      ResourceId: !Ref ApiGatewayResource
      HttpMethod: Get
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        Credentials: !GetAtt ApiRole.Arn
        TimeoutInMillis: 29000
        IntegrationHttpMethod: Get
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Function.Arn}/invocations'

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ""
            Effect: "Allow"
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /

  Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref Function
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayId}/*

  ApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ""
            Effect: "Allow"
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  ApiPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ["${Prefix}GetHealthLambdaAccess", { Prefix: !Ref Prefix }]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "lambda:*"
            Resource: !GetAtt Function.Arn
      Roles:
        - !Ref ApiRole
