AWSTemplateFormatVersion: 2010-09-09
Description: The game checker S3 bucket for code

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}
      VersioningConfiguration:
        Status: Enabled

Outputs:
  ArtifactBucketId:
    Value: !Ref ArtifactBucket
    Description: The id of the build repository for the Game Checker appliation.
    Export:
      Name: ArtifactBucketId