version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "installing base packages"
      - npm i

      - echo Installing API packages
      - npm run install:api
  build:
    commands:
      - echo "building packages"
      - npm run build:api

      - echo "packaging packages"
      - npm run package:api
  post_build:
    commands:
      - echo Testing API
      - npm run test:api

      - echo Testing Finished

artifacts:
  files:
    - '*'
  secondary-artifacts:
    apiGatewayBuildOutput:
      base-directory: infrastructure/apiGateway
      files:
        - '**/*'
    apiGatewayDeploymentBuildOutput:
      base-directory: infrastructure/apiGatewayDeployment
      files:
        - '**/*'