version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "installing base packages"
      - npm i
  build:
    commands:
      - echo "packaging packages"
      - npm run package:data

      - echo "Listing infra dir"
      - ls -R infrastructure/database || echo "No database dir found"

artifacts:
  files:
    - '*'
  secondaryArtifacts:
    databaseBuildOutput:
      base-directory: 'infrastructure/database'
      files:
        - '**/*'