version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "installing base packages"
      - npm i
  build:
    commands:
      - echo "packaging packages"
      - npm run package:data

      - pwd
      - ls -l
      - cd ./infrastructure/database
      - ls -l

artifacts:
  files:
    - '*'
  secondary-artifacts:
    databaseBuildOutput:
      base-directory: 'infrastructure/database'
      files:
        - '**/*'