version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing base packages
      - npm i

      - echo Installing UI packages
      - npm run install:ui
  build:
    commands:
      - echo Build started for ui
      - npm run build:ui
  post_build:
    commands:
      - echo Installing chrome for testing
      - apt-get update && apt-get install -y google-chrome-stable

      - echo Testing UI
      - npm run test:ui

cache:
  paths:
    - 'node_modules/**/*'

artifacts:
  files:
    - '*'
  secondary-artifacts:
    uiBuildOutput:
      # name: game-checker-$(date +%Y-%m-%d)
      base-directory: ui/www
      files:
        - '**/*'
    # urlBuildOutput:
    #   base-directory: infrastructure/url
    #   files:
    #     - '**/*'