version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing Chrome
      - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google.list
      - apt-get update
      - apt-get install -y google-chrome-stable
      - google-chrome --version

      - echo Installing base packages
      - npm i

      - echo Installing UI packages
      - npm run install:ui
  build:
    commands:
      - echo Build started for ui
      - npm run build:ui

      - echo "packaging packages"
      - npm run package:ui
  post_build:
    commands:
      - echo Testing UI
      - npm run test:ui

      - echo Testing Finished

artifacts:
  files:
    - '*'
  secondary-artifacts:
    uiBuildOutput:
      base-directory: ui/dist/*/browser
      files:
        - '**/*'
    urlBuildOutput:
      base-directory: infrastructure/url
      files:
        - '**/*'