version: 0.2

phases:
  pre_build:
    commands:
      - echo "Deploying Health Lambda..."
      - echo "Lambda Role ARN - $LAMBDA_ROLE_ARN"
      - echo "Copying built artifacts from secondary source..."
      - cp -r $CODEBUILD_SRC_DIR_LambdasBuildOutput/api/health/dist api/health/ || echo "No health dist"
      - echo "Copying built artifacts from secondary source..."
      - cp -r $CODEBUILD_SRC_DIR_LambdasBuildOutput/api/health/dist api/health/ || echo "No health dist"

  build:
    commands:
      - |
        API_ID=$(aws apigatewayv2 get-apis --region $AWS_REGION --query "Items[?Name=='${ENVIRONMENT}-GameCheckerAPI'].ApiId" --output text)
        export API_ID
        echo "API ID: $API_ID"
      
      - cd api/health
      - |
        export FUNCTION_NAME="${ENVIRONMENT}-HealthCheck"
        export API_NAME="${ENVIRONMENT}-GameCheckerAPI"
        node dist/deploy.js
      - cd ../..

  post_build:
    commands:
      - echo "✅ Health Lambda deployed!"
