version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
      
  pre_build:
    commands:
      - echo "Running Lambda function tests..."
      
  build:
    commands:
      - echo "Testing api/health..."
      - |
        if [ -f "api/health/package.json" ] && grep -q '"test"' api/health/package.json; then
          cd api/health && npm test && cd ../..
        else
          echo "No tests found for health endpoint"
        fi
      - echo "Testing api/v1/settings/get..."
      - |
        if [ -f "api/v1/settings/get/package.json" ] && grep -q '"test"' api/v1/settings/get/package.json; then
          cd api/v1/settings/get && npm test && cd ../../../..
        else
          echo "No tests found for settings GET endpoint"
        fi
      - echo "Testing api/v1/settings/put..."
      - |
        if [ -f "api/v1/settings/put/package.json" ] && grep -q '"test"' api/v1/settings/put/package.json; then
          cd api/v1/settings/put && npm test && cd ../../../..
        else
          echo "No tests found for settings PUT endpoint"
        fi
      - echo "Testing api/v1/user/post..."
      - |
        if [ -f "api/v1/user/post/package.json" ] && grep -q '"test"' api/v1/user/post/package.json; then
          cd api/v1/user/post && npm test && cd ../../../..
        else
          echo "No tests found for user POST endpoint"
        fi
      
  post_build:
    commands:
      - echo "Lambda tests completed"

artifacts:
  files:
    - 'api/**/*'
  name: LambdasTestArtifact
