version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing AWS CLI and dependencies..."
      
  pre_build:
    commands:
      - echo "Preparing for deployment to AWS"
      - echo "AWS Region - $AWS_REGION"
      - echo "Environment - $ENVIRONMENT"
      - aws --version
      - echo "Retrieving Google OAuth credentials if auth enabled..."
      - |
        if [ "$ENABLE_AUTH" = "true" ] && [ -n "$GOOGLE_CREDENTIALS_SECRET_ARN" ]; then
          echo "Retrieving Google OAuth credentials from Secrets Manager..."
          GOOGLE_CLIENT_ID=$(aws secretsmanager get-secret-value --secret-id $GOOGLE_CREDENTIALS_SECRET_ARN --region $AWS_REGION --query 'SecretString' --output text | jq -r '.client_id')
          export GOOGLE_CLIENT_ID
          echo "Google Client ID retrieved successfully"
        else
          echo "Authentication disabled or no secret ARN provided"
          export GOOGLE_CLIENT_ID=""
        fi

  build:
    commands:
      - echo "Deploying infrastructure..."
      - echo "Current directory:" && pwd
      - echo "Listing root:" && ls -la
      - echo "Listing infrastructure:" && ls -la infrastructure/
      - echo "Listing infrastructure/database:" && ls -la infrastructure/database/
      - echo "Deploying DynamoDB table..."
      - cd infrastructure/database
      - |
        export TABLE_NAME="${ENVIRONMENT}-GameCheckerTable"
        export AWS_ENDPOINT=""
        node dist/create-table.js
      - cd ../..
      - echo "Deploying API Gateway..."
      - cd infrastructure/apiGateway
      - |
        export API_NAME="${ENVIRONMENT}-GameCheckerAPI"
        export AWS_ENDPOINT=""
        node dist/create-api.js
      - cd ../..
      - echo "Getting API ID..."
      - |
        API_ID=$(aws apigatewayv2 get-apis --region $AWS_REGION --query "Items[?Name=='${ENVIRONMENT}-GameCheckerAPI'].ApiId" --output text)
        export API_ID
        echo "API ID: $API_ID"
      - echo "Deploying Health Check Lambda..."
      - cd api/health
      - |
        export FUNCTION_NAME="${ENVIRONMENT}-HealthCheck"
        export API_NAME="${ENVIRONMENT}-GameCheckerAPI"
        export AWS_ENDPOINT=""
        node dist/deploy.js
      - cd ../..
      - echo "Deploying Settings GET Lambda..."
      - cd api/v1/settings
      - |
        export FUNCTION_NAME="${ENVIRONMENT}-SettingsGet"
        export API_NAME="${ENVIRONMENT}-GameCheckerAPI"
        export AWS_ENDPOINT=""
        export ENABLE_AUTH="${ENABLE_AUTH:-true}"
        export GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID}"
        node dist/deploy.js
      - cd ../..
      
  post_build:
    commands:
      - echo "Deployment completed successfully!"
      - echo "Fetching deployed endpoints..."
      - |
        API_ID=$(aws apigatewayv2 get-apis --region $AWS_REGION --query "Items[?Name=='${ENVIRONMENT}-GameCheckerAPI'].ApiId" --output text)
        export API_ID
        echo "=== Deployment Summary ==="
        echo "API ID - $API_ID"
        echo "API Endpoint - https://$API_ID.execute-api.$AWS_REGION.amazonaws.com"
        echo ""
        echo "Available Routes:"
        aws apigatewayv2 get-routes --api-id $API_ID --region $AWS_REGION --query "Items[].RouteKey" --output table

artifacts:
  files:
    - '**/*'
  name: DeployArtifact
