AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for a basic AWS CodePipeline with GitHub source.

Parameters:
  GitHubRepo:
    Type: String
    Description: GitHub repository name
  GitHubBranch:
    Type: String
    Default: main
    Description: GitHub branch to use
  Prefix:
    Type:  String
    AllowedPattern: "[A-Za-z0-9-]*"
    Default: ''
  ConnectionArn:
    Type: String
    Default: arn:aws:codestar-connections:us-east-2:625961017727:connection/760e3889-f416-44aa-9c62-001a92098608
    Description: The CodePipeline connection to Github

Conditions:
  IsProduction: !Equals [!Ref GitHubBranch, "main"]

Resources:
  PipelineArtifactBucket:
    Type: AWS::S3::Bucket

  UiBuildRunner:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ["${Prefix}UiBuildRunner", { Prefix: !Ref Prefix}] 
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: BUILD_OUTPUT_BUCKET
            Value: !ImportValue ArtifactBucketId
          - Name: S3_BUCKET
            Value: !ImportValue ArtifactBucketId
      ServiceRole: !ImportValue BuildExecutionRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: infrastructure/pipeline/buildspecs/ui-build.yaml

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !ImportValue PipelineInfrastructureRoleArn
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              OutputArtifacts:
                - Name: SourceCode
              Configuration:
                ConnectionArn: !Ref ConnectionArn
                FullRepositoryId: !Sub "{{resolve:secretsmanager:Github:SecretString:owner}}/${GitHubRepo}"
                BranchName: !Ref GitHubBranch
                OutputArtifactFormat: CODE_ZIP
              RunOrder: 1
        - Name: Build
          Actions:
          - Name: BuildUi
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: 1
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref UiBuildRunner
            InputArtifacts:
              - Name: SourceCode
            OutputArtifacts:
              - Name: uiBuildOutput
              - Name: urlBuildOutput
            RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: DeployUrl
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: urlBuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !ImportValue CloudFormationExecutionRoleArn
                TemplatePath: urlBuildOutput::infrastructure/template.package.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                StackName: !Sub ["${Prefix}Stack-Stack-Url", { "Prefix": !Ref Prefix }]
                ParameterOverrides: !Sub
                  - '{ "Domain": "${Domain}", "BranchName": "${BranchName}" }'
                  - Domain: !If [IsProduction, 'doiownthatgame.com', !Sub '${GitHubBranch}.doiownthatgame.com']
                    BranchName: !Ref GitHubBranch
              RunOrder: 1
            - Name: DeployUiCode
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                BucketName: !ImportValue UiBucketName
                Extract: true
                ObjectKey: !If [IsProduction, 'master', !Ref GitHubBranch]
              InputArtifacts:
                - Name: uiBuildOutput
              Region: us-east-1
              RunOrder: 2

Outputs:
  PipelineName:
    Description: Name of the created CodePipeline
    Value: !Ref CodePipeline