AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for a basic AWS CodePipeline with GitHub source.

Parameters:
  GitHubRepo:
    Type: String
    Description: GitHub repository name
  GitHubBranch:
    Type: String
    Default: main
    Description: GitHub branch to use
  Prefix:
    Type:  String
    AllowedPattern: "[A-Za-z0-9-]*"
    Default: ''

Conditions:
  IsProduction: !Equals [!Ref GitHubBranch, "main"]

Resources:
  PipelineArtifactBucket:
    Type: AWS::S3::Bucket

  UiBuildRunner:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ["${Prefix}UiBuildRunner", { Prefix: !Ref Prefix}] 
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: BUILD_OUTPUT_BUCKET
            Value: !ImportValue ArtifactBucketId
          - Name: S3_BUCKET
            Value: !ImportValue ArtifactBucketId
      ServiceRole: !ImportValue BuildExecutionRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: infrastructure/pipeline/buildspecs/ui-build.yaml

  ApiBuildRunner:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ["${Prefix}ApiBuildRunner", { Prefix: !Ref Prefix}]
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: BUILD_OUTPUT_BUCKET
            Value: !ImportValue ArtifactBucketId
          - Name: S3_BUCKET
            Value: !ImportValue ArtifactBucketId
      ServiceRole: !ImportValue BuildExecutionRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: infrastructure/pipeline/buildspecs/api-build.yaml

  DataBuildRunner:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ["${Prefix}DataBuildRunner", { Prefix: !Ref Prefix}] 
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: BUILD_OUTPUT_BUCKET
            Value: !ImportValue ArtifactBucketId
          - Name: S3_BUCKET
            Value: !ImportValue ArtifactBucketId
      ServiceRole: !ImportValue BuildExecutionRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: infrastructure/pipeline/buildspecs/data-build.yaml

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref GitHubBranch
      RoleArn: !ImportValue PipelineInfrastructureRoleArn
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceCode
              Configuration:
                Owner: "{{resolve:secretsmanager:Github:SecretString:owner}}"
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                PollForSourceChanges: false
                OAuthToken: "{{resolve:secretsmanager:Github:SecretString:token}}"
              RunOrder: 1
        - Name: Build
          Actions:
          - Name: BuildUi
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: 1
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref UiBuildRunner
            InputArtifacts:
              - Name: SourceCode
            OutputArtifacts:
              - Name: uiBuildOutput
              - Name: urlBuildOutput
            RunOrder: 1
          - Name: BuildApi
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: 1
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref ApiBuildRunner
            InputArtifacts:
              - Name: SourceCode
            OutputArtifacts:
              - Name: apiGatewayBuildOutput
              - Name: apiGatewayDeploymentBuildOutput
            RunOrder: 1
          - Name: BuildData
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: 1
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref DataBuildRunner
            InputArtifacts:
              - Name: SourceCode
            OutputArtifacts:
              - Name: databaseBuildOutput
            RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: DeployDatabase
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: databaseBuildOutput
              Namespace: db
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !ImportValue CloudFormationExecutionRoleArn
                TemplatePath: databaseBuildOutput::infrastructure/template.package.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: !Sub ["${Prefix}Database", { Prefix: !Ref Prefix}] 
                ParameterOverrides: !Sub |
                  {
                    "Prefix": "${Prefix}"
                  }
              RunOrder: 1
            - Name: DeployUrl
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: urlBuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !ImportValue CloudFormationExecutionRoleArn
                TemplatePath: urlBuildOutput::infrastructure/template.package.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                StackName: !Sub ["${Prefix}Stack-Stack-Url", { "Prefix": !Ref Prefix }]
                ParameterOverrides: !Sub
                  - '{ "Domain": "${Domain}", "BranchName": "${BranchName}" }'
                  - Domain: !If [IsProduction, 'doiownthatgame.com', !Sub '${GitHubBranch}.doiownthatgame.com']
                    BranchName: !Ref GitHubBranch
              RunOrder: 1
            - Name: DeployUiCode
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                BucketName: !ImportValue UiBucketName
                Extract: true
                ObjectKey: !If [IsProduction, 'master', !Ref GitHubBranch]
              InputArtifacts:
                - Name: uiBuildOutput
              Region: us-east-1
              RunOrder: 2
            - Name: DeployApi
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: apiGatewayBuildOutput
              Namespace: api
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !ImportValue CloudFormationExecutionRoleArn
                TemplatePath: apiGatewayBuildOutput::template.package.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                StackName: !Sub ["${Prefix}Stack-API", { "Prefix": !Ref Prefix }]
                ParameterOverrides: !Sub |
                  {
                    "Prefix": "${Prefix}"
                  }
              RunOrder: 2
            - Name: DeployApiStage
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: apiGatewayDeploymentBuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !ImportValue CloudFormationExecutionRoleArn
                TemplatePath: apiGatewayDeploymentBuildOutput::template.package.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                StackName: !Sub ["${Prefix}Stack-Stack-Api-Deployment", { "Prefix": !Ref Prefix }]
                ParameterOverrides: !Sub
                  - '{ "BasePathDomain": "${BasePathDomain}", "ApiGatewayId": "#{api.ApiGatewayId}" }'
                  - BasePathDomain: !If [IsProduction, 'api.doiownthatgame.com', !Sub 'api-${GitHubBranch}.doiownthatgame.com']
              RunOrder: 3

Outputs:
  PipelineName:
    Description: Name of the created CodePipeline
    Value: !Ref CodePipeline