AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: The Game Checker V1 Steam api gateway code

Parameters:
  HttpApi:
    Type: String
    Description: The ID of the API Gateway this method should be attached to.
  AuthorizerId:
    Type: String
    Description: The ID of the authorizer
  TableName:
    Type: String
    Description: The name of the database table
  Prefix:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]*"

Resources:
  SteamPut:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./put/template.yaml
      Parameters:
        HttpApi: !Ref HttpApiId
        RootResourceId: !GetAtt V1Path.ResourceId
        AuthorizerId: !Ref AuthorizerId
        TableName: !Ref TableName
        Prefix: !Ref Prefix