AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: The Game Changer api gateway deployment

Parameters:
  BasePathDomain:
    Type: String
    Default: ''
  HostedZoneId:
    Type: String
    Default: Z02241462DXLIC7B4J76X
  HttpApiId:
    Type: String

Resources:
  # Stage with auto deploy
  HttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: '$default'
      AutoDeploy: true
      
  # Custom Domain for HTTP API
  HttpApiDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Ref BasePathDomain
      DomainNameConfigurations:
        - CertificateArn: !ImportValue CloudFrontCertArn
          EndpointType: REGIONAL

  # Mapping the domain to your API
  HttpApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref HttpApiId
      DomainName: !Ref HttpApiDomainName
      Stage: '$default'
    DependsOn: HttpApiDomainName

  # Route53 alias record for the custom domain
  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt HttpApiDomainName.RegionalDomainName
        HostedZoneId: !GetAtt HttpApiDomainName.RegionalHostedZoneId
        EvaluateTargetHealth: false
      HostedZoneId: !Ref HostedZoneId
      Name: !Join [ "", [ !Ref BasePathDomain, "." ] ]
      Type: A