name: Ephemeral Environment

on:
  push:
    branches:
      - "*"   # create/update on push to feature branches
  pull_request:
    types: [closed]   # teardown when PR closes

jobs:
  ephemeral-env:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set env vars
        run: |
          echo "BRANCH_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "STACK_NAME=ephemeral-${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Create/Update stack
        if: github.event_name == 'push'
        run: |
          aws cloudformation deploy \
            --template-file infra/ephemeral-pipeline.yml \
            --stack-name $STACK_NAME \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides BranchName=$BRANCH_NAME

      - name: Trigger pipeline
        if: github.event_name == 'push'
        run: |
          PIPELINE_NAME="ephemeral-${BRANCH_NAME}-pipeline"
          aws codepipeline start-pipeline-execution --name $PIPELINE_NAME

      - name: Delete stack (teardown)
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: |
          aws cloudformation delete-stack --stack-name $STACK_NAME
